name: 'BuildJet Cache Delete'
description: 'An action to delete a BuildJet Cache entry'
author: 'BuildJet'
inputs:
  cache_key:
    description: 'Cache Key to Delete'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
