name: Delete BuildJet Cache
on:
  workflow_dispatch:
    inputs:
      cache_key:
        description: 'BuildJet Cache Key to Delete'
        required: true
        type: string

jobs:
  delete-buildjet-cache:
    name: Deleting BuildJet Cache entry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        with:
          cache_key: ${{ inputs.cache_key }}
